<a href="https://colab.research.google.com/github/terrydlek/first-project/blob/master/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5(%EC%8B%A0%EA%B2%BD%EB%A7%9D_softmax_function).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [ ]:
#softmax function 함수 구현
def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a
  return y
#but 위 함수는 오버플로 문제를 가지고 있음

In [7]:
import numpy as np
a = np.array([1010, 1000, 990]) #소프트맥스 함수의 계산
print(np.exp(a) / np.sum(np.exp(a))) #제대로 계산되지 않음

c = np.max(a) #c = 1010 (최댓값)
print(a - c)
print(np.exp(a - c) / np.sum(np.exp(a - c))) #입력 신호 중 최댓값을 빼주면 올바르게 계산할 수 있음

[nan nan nan]
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [8]:
#오버플로 문제를 해결한 소프트맥스 함수 구현
def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a
  return y

In [11]:
#softmax() 함수를 사용하면 신경망의 출력을 계산할 수 있음
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y) #소프트맥스 함수의 출력은 0에서 1.0 사이의 실수 (소프트맥스 함수의 중요한 성질)
print(np.sum(y)) #출력의 총합은 1 (소프트맥스 함수의 중요한 성질) ==> 확률로 해석할 수 있음 ==> 문제를 통계적으로 대응할 수 있게 됨

[0.01821127 0.24519181 0.73659691]
1.0
