<a href="https://colab.research.google.com/github/terrydlek/first-project/blob/master/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5(%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EB%8B%A4%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4%EC%9D%98_%EA%B3%84%EC%82%B0).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A)) #배열의 차원 수
print(A.shape) #배열의 형상(튜플로 변환 주의!)
print(A.shape[0])

B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
print(np.ndim(B))
print(B.shape)

[1 2 3 4]
1
(4,)
4
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [24]:
#행렬의 내적
A = np.array([[1, 2], [3, 4]])
print(A.shape)
B =  np.array([[5, 6], [7, 8]])
print(B.shape)
print(np.dot(A,B)) # 두 행렬의 내적 계산

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


In [27]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)

B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)

print(np.dot(A, B))

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


In [28]:
import numpy as np

A = np.array([[1,2],[3,4],[5,6]])
print(A.shape)

B = np.array([7, 8])
print(B.shape)

print(np.dot(A, B))

(3, 2)
(2,)
[23 53 83]


In [30]:
import numpy as np

X = np.array([1, 2])
print(X.shape)
W = np.array([[1,3,5], [2,4,6]])
print(W)
print(W.shape)
Y = np.dot(X,W)
print(Y)

(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]


In [36]:
#3층 신경망: 입력층(0층)은 2개, 첫 번재 츤닉층(1층)은 3개, 두 번째 은닉층(2층)은 2개, 출력층(3층)은 2개의 뉴런으로 구성
#입력층에서 1층으로의 신호 전달
import numpy as np

X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5], [0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)
A1 = np.dot(X, W1) + B1
print(A1)

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1)
print(Z1)
print("--------------------------------------")
#1층에서 2층으로의 신호 전달
#1층의 출력 Z1이 2층의 입력이 된다는 점을 제외하면 위의 구현과 같음
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1,W2) + B2
Z2 = sigmoid(A2)

print(Z2)
print("--------------------------------------")
#2층에서 출력층으로의 신호 전달
#출력증의 구현도 그동안의 구현과 거의 같으나 활성화 함수만 지금까지의 은닉층과 다름
def identity_function(x): #항등함수
  return x

W3 = np.array([[0.1,0.3], [0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2,W3) + B3
Y = identity_function(A3)

print(Y)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]
--------------------------------------
(3,)
(3, 2)
(2,)
[0.62624937 0.7710107 ]
--------------------------------------
[0.31682708 0.69627909]


In [37]:
import numpy as np

def init_network(): #가중치와 편향을 초기화, 이들을 딕셔너리 변수인 network에 저장. 이 딕셔너리 변수 network에는 각 층에 필요한 매개변수(가중치와 편향)를 저장
  network = {}
  network['W1'] = np.array([[0.1,0.3,0.5], [0.2,0.4,0.6]])
  network["b1"] = np.array([0.1,0.2,0.3])
  network["W2"] = np.array([[0.1,0.4], [0.2,0.5], [0.3,0.6]])
  network["b2"] = np.array([0.1,0.2])
  network["W3"] = np.array([[0.1,0.3], [0.2,0.4]])
  network["b3"] = np.array([0.1,0.2])
  return network

def forward(network,x): #입력 신호를 출력으로 변환하는 처리 과정을 모두 구현
  W1,W2,W3 = network["W1"], network["W2"], network["W3"]
  b1,b2,b3 = network["b1"], network["b2"], network["b3"]

  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1)
  a2 = np.dot(z1,W2) + b2
  z2 = sigmoid(a2)
  a3 = np.dot(z2, W3) + b3
  y = identity_function(a3)
  return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
