<a href="https://colab.research.google.com/github/terrydlek/first-project/blob/master/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x / 2.0)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[0.5 1.  1.5]


In [21]:
A = np.array([[1,2], [3,4]])
print(A)
print(A.shape)
print(A.dtype)
B = np.array([[3,0], [0,6]])
print(A + B)
print(A * B)
print(A * 10)

[[1 2]
 [3 4]]
(2, 2)
int64
[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]
[[10 20]
 [30 40]]


In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(a * b)

[[10 40]
 [30 80]]


In [35]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print(X[0])
print(X[0][1])
for row in X:
  print(row)

X = X.flatten()#X를 1차원 배열로 변환(평탄화)
print(X)
print(X[np.array([0, 2, 4])]) #인덱스가 0,2,4인 원소 얻기
print(X > 15) #특정 조건을 만족하는 원소 얻기
print(X[X > 15])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55
[51 55]
[14 19]
[0 4]
[51 55 14 19  0  4]
[51 14  0]
[ True  True False  True False False]
[51 55 19]
